Models/ApproveListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Deestone.Models
{
  public class ApproveListViewModel
  {
    public List<TempBomDetailModel> BOMLISTAPPROVE { get; set; }
    public List<BomApproveRemarkModel> BOMREMARK { get; set; }
    public string EMAIL { get; set; }
    public string NONCE { get; set; }
    public List<BomRecIdModel> BOM_RECID { get; set; }
  }
}

Models/BomDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Deestone.Models
{
  public class BomDetailViewModel
  {
    public List<BomDetailModel> BOM_DETAIL { get; set; }
    public List<BomApproveRemarkModel> BOM_REMARK { get; set; }
    public string REMARK { get; set; }
  }

  public class BomDetail
  {
    public string BOMID { get; set; }
    public string ITEMID { get; set; }
    public string ITEMNAME { get; set; }
    public string LOG_ITEMNAME { get; set; }
    public double LINENUM { get; set; }
    public double BOMQTY { get; set; }
    public string UNITID { get; set; }
    public double BOMQTYSERIE { get; set; }
    public int DSG_LOGBOMID { get; set; }
    public string LOG_BOMITEMID { get; set; }
    public double LOG_LINENUM { get; set; }
    public double LOG_BOMQTY { get; set; }
    public string LOG_UNITID { get; set; }
    public double PERSERIES { get; set; }
    public int AX_STATUS { get; set; }
    public string BOMNAME { get; set; }
  }
}

Models/ResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Deestone.Models
{
    public class ResultViewModel
    {
        public bool result { get; set; }
        public string message { get; set; }
    }
}

Controllers/BomApiController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Deestone.Services;
using MimeKit;
using MailKit.Net.Smtp;
using MailKit.Security;
using Deestone.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;

namespace Deestone.Controllers
{
    public class BomApiController : Controller
    {
        BomService bomService = new BomService();
        EmailService emailService = new EmailService();
        DataService dataService = new DataService();
        NonceService nonceService = new NonceService();

        private IConfiguration _configuration;

        public BomApiController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        [HttpGet]
        public JsonResult GenApproveFlow()
        {
            try
            {
                var generateApproveFlow = bomService.GenerateApproveFlow();

                if (generateApproveFlow.result == false)
                {
                    throw new Exception(generateApproveFlow.message);
                }

                return Json(generateApproveFlow);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
            
        }

        [HttpGet]
        public JsonResult GetBomFromAx()
        {
            try
            {
                var getBomFromAx = bomService.GetBomFromAx();

                if (getBomFromAx.result == false)
                {
                    throw new Exception(getBomFromAx.message);
                }

                //var generateApproveFlow = bomService.GenerateApproveFlow();

                //if (generateApproveFlow.result == false)
                //{
                //    throw new Exception(generateApproveFlow.message);
                //}

                //var generateEmail = GenerateTempSendMail();

                //if (generateEmail.result == false)
                //{
                //    throw new Exception(generateEmail.message);
                //}

                //var sendEmailApproveResult = SendEmailApprove_v2();

                //if (sendEmailApproveResult.result == false)
                //{
                //    throw new Exception(sendEmailApproveResult.message);
                //}

                return Json(new ResponseModel
                {
                    result = true,
                    message = "Get data success."
                });
            }
            catch (Exception ex)
            {
                return Json(new ResponseModel
                {
                    result = false,
                    message = ex.Message
                });
            }
        }

        [NonAction]
        public ResponseModel SendEmailApprove(
            int bomRecId = 0,
            bool resultBomStatus = false,
            bool resultBom = false,
            int notifyTo = 0,
            bool sendAll = false)
        {
            // bomReId != 0 คือ send email final approve
            // bomRecId == 0 หรือว่าง คือ ส่ง email approve ปรกติ

            // resultBom คือ complete bom นั้นแล้ว ไม่ว่าจะ approve หรือ reject
            try
            {
                var resultSendEmail = new List<string>();
                var emailLists = new List<GetEmailFromBomModel>();
                var emailToSendEmail = new List<GetEmailFromBomModel>();
                var bom = new List<GetBomSendEmailModel>();

                if (bomRecId != 0)
                {
                    bom = bomService.GetBomSendEmail(bomRecId);
                }
                else
                {
                    bom = bomService.GetBomSendEmail();
                }

                if (bom.Count == 0)
                {
                    return new ResponseModel
                    {
                        result = true,
                        message = "No bom to send an email."
                    };
                }

                foreach (var bomRow in bom)
                {
                    if (sendAll == true)
                    {
                        emailToSendEmail = bomService.GetEmailFromBom(bomRow.BOMID, bomRow.COMPANY_REF, notifyTo, true);
                    }
                    else
                    {
                        emailToSendEmail = bomService.GetEmailFromBom(bomRow.BOMID, bomRow.COMPANY_REF, notifyTo);
                    }


                    if (emailToSendEmail.Count > 0)
                    {
                        foreach (var email in emailToSendEmail)
                        {
                            emailLists.Add(email);
                        }
                    }
                }

                foreach (var email in emailLists)
                {
                    var emailBody = @"";

                    emailBody += @"<div 
                        style='font-size: 16px; 
                        font-family: Arial, Helvetica, sans-serif; 
                        font-weight: bold; 
                        padding: 10px;
                        margin-bottom: 10px;'>" + GetSubjectEmail(email.AX_STATUS, email.BOMID) + @"</div>";

                    emailBody += @"<div 
                        style='font-size: 16px; 
                        font-family: Arial, Helvetica, sans-serif; 
                        font-weight: bold; 
                        padding: 10px;'>รายละเอียดการเปลี่ยนแปลง</div>";

                    var bomVersionDetail = bomService.GetBomVersionDetail(email.BOMID);

                    foreach (var item in bomVersionDetail)
                    {
                        emailBody += @"<table
                          width='100%'
                          cellspacing='0'
                          cellpadding='5'
                          border='1'
                          style='font-size: 14px; font-family: Arial, Helvetica, sans-serif; margin-bottom: 30px; max-width: 500px;'
                        >
                          <thead style='background: #333333; color: #ffffff;'>
                            <th>DETAIL</th>
                            <th>OLD</th>
                            <th>NEW</th>
                          </thead>
                          <tbody>";

                        emailBody += @"<tr>
                              <td style='width: 30%;'>ITEM</td>
                              <td style='text-align: center;'>" + item.LOG_BOMITEMID + @"</td>
                              <td style='text-align: center;'>" + item.ITEMID + @"</td>
                            </tr>
                            <tr>
                              <td style='width: 30%;'>BOM QTY</td>
                              <td style='text-align: center;'>" + item.LOG_BOMQTY + @"</td>
                              <td style='text-align: center;'>" + item.BOMQTY + @"</td>
                            </tr>
                            <tr>
                              <td style='width: 30%;'>UNIT</td>
                              <td style='text-align: center;'>" + item.LOG_UNITID + @"</td>
                              <td style='text-align: center;'>" + item.UNITID + @"</td>
                            </tr>
                            <tr>
                              <td style='width: 30%;'>BOM QTY SERIES</td>
                              <td style='text-align: center;'>" + item.BOMQTYSERIE + @"</td>
                              <td style='text-align: center;'>" + item.PERSERIES + @"</td>
                            </tr>";

                        emailBody += @"</tbody></table>";
                    }

                    emailBody += @"<div 
                        style='font-size: 16px; 
                        font-family: Arial, Helvetica, sans-serif; 
                        font-weight: bold; 
                        padding: 10px;'>ไอเทมที่จะได้รับผลกระทบ</div>";

                    var itemRelate = bomService.GetItemRelateBomVersion(email.BOMID);

                    emailBody += @"<table
                      width='100%'
                      cellspacing='0'
                      cellpadding='5'
                      border='1'
                      style='font-size: 14px; font-family: Arial, Helvetica, sans-serif;
                      max-width: 500px;'
                    >
                      <thead style='background: #333333; color: #ffffff;'>
                        <th>ITEM ID</th>
                        <th>ITEM NAME</th>
                      </thead>
                      <tbody>";


                    foreach (var item in itemRelate)
                    {
                        emailBody += @"<tr>
                          <td style='text-align: center;'>" + item.ITEMID + @"</td>
                          <td> " + item.ITEM_NAME + @"</td>
                        </tr>";
                    }

                    emailBody += @"</tbody></table>";

                    var remarks = bomService.GetRemarkByBom(email.BOM_RECID);

                    if (remarks.Count > 0)
                    {
                        emailBody += @"<div style='text-align: left; 
                              font-size: 16px; 
                              margin: 30px 0px; 
                              max-width: 500px;
                              font-family: Arial, Helvetica, sans-serif; clear: both;'>
                              <div 
                                style='font-size: 16px; 
                                font-family: Arial, Helvetica, sans-serif; 
                                font-weight: bold; 
                                padding: 10px;'>หมายเหตุเพิ่มเติม</div>";

                        foreach (var item in remarks)
                        {
                            string approveText = "";

                            if (item.APPROVE == 1)
                            {

Controllers/BomController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Deestone.Services;
using Deestone.Models;

namespace Deestone.Controllers
{
  public class BomController : Controller
  {
    NonceService nonceService = new NonceService();
    BomService bomService = new BomService();
    AuthService authService = new AuthService();

    [HttpGet]
    public IActionResult SubmitResult(int bom, int email, int trans, string id, string company, string nonce, int approve)
    {
      try
      {
        ViewData["BomRedId"] = bom;
        ViewData["EmailRecId"] = email;
        ViewData["ApproveTransId"] = trans;
        ViewData["BomId"] = id;
        ViewData["Company"] = company;
        ViewData["Nonce"] = nonce;
        ViewData["isApprove"] = approve;

        if (approve == 1)
        {
          ViewData["Approve"] = "อนุมัติ";
        }
        else
        {
          ViewData["Approve"] = "ไม่อนุมัติ";
        }


        return View("SubmitResult");
      }
      catch (Exception ex)
      {
        return Ok(ex.Message);
      }
    }

    [HttpGet]
    public IActionResult Result(int result, string bom)
    {
      try
      {
        ViewData["bom"] = bom;

        string message = "";

        if (result == 1)
        {
          message += "อนุมัติ BOM VERSION : " + bom + " เสร็จสิ้น";
        }
        else if (result == 2)
        {
          message += "ไม่อนุมัติ BOM VERSION : " + bom + " เสร็จสิ้น";
        }
        else if (result == 3)
        {
          message = "รายการนี้ถูกดำเนินการไปแล้ว";
        }

        ViewData["message"] = message;

        return View("Result");
      }
      catch (Exception ex)
      {
        return Ok(ex.Message);
      }
    }

    [HttpGet]
    public IActionResult Index()
    {
      if (authService.IsLogin(HttpContext.Request).result == false)
      {
        return Redirect("/user/login");
      }

      return View("Bom");
    }

    [HttpGet]
    public IActionResult ApproveList(string email, string nonce)
    {
      try
      {
        var validateNonce = nonceService.ValidateNonce(nonce);

        if (validateNonce.result == false)
        {
          throw new Exception(validateNonce.message);
        }

        var approveList = bomService.GetBomListApprove(email);

        if (approveList.Count == 0)
        {
          throw new Exception("ไม่มีรายการ Approve.");
        }

        var bomRecId = bomService.GetBomRecIdFromEmailSendApprove(email);

        var bom = new ApproveListViewModel
        {
          BOMLISTAPPROVE = approveList,
          BOMREMARK = bomService.GetBomRemark(),
          EMAIL = email,
          NONCE = nonce,
          BOM_RECID = bomRecId
          // BOM_RECID = bomRecId[0].BOM_RECID
        };


        return View("ApproveList", bom);
      }
      catch (Exception ex)
      {
        var _data = new ResultViewModel
        {
          result = false,
          message = ex.Message
        };

        return View("Result", _data);
      }
    }

    [HttpGet]
    public IActionResult BomDetail(string bomid, int bid)
    {
      try
      {
        // return Json(bomService.GetBomVersionDetail_v3(bomid));
        var bom = new BomDetailViewModel
        {
          BOM_DETAIL = bomService.GetBomVersionDetail_v4(bomid),
          BOM_REMARK = bomService.GetBomRemarkByBomId(bid),
          REMARK = bomService.GetBomRemarkFromAx(bomid)
        };

        return View("BomDetail", bom);
      }
      catch (Exception ex)
      {
        return BadRequest(ex.Message);
      }

    }

    [HttpPost]
    public IActionResult GetBomLists()
    {
      try
      {
        return Ok("");
      }
      catch (Exception)
      {

        throw;
      }
    }

    [HttpPost]
    public JsonResult GetItemGroup()
    {
      try
      {
        var rows = bomService.GetItemGroup();
        return Json(rows);
      }
      catch (Exception ex)
      {
        return Json(ex.Message);
      }
    }

    [HttpPost]
    public JsonResult GetNotifyToEmail()
    {
      try
      {
        var rows = bomService.GetNotifyToEmail();
        return Json(rows);
      }
      catch (System.Exception)
      {

        throw;
      }
    }

    [HttpPost]
    public JsonResult GetBomAll()
    {
      try
      {
        var rows = bomService.GetBomAll();
        return Json(new
        {
          draw = 1,
          recordsTotal = rows.Count,
          recordsFiltered = rows.Count,
          data = rows
        });
      }
      catch (System.Exception)
      {

        throw;
      }
    }

    [HttpPost]
    public JsonResult GetBomApproveTrans(int id)
    {
      try
      {
        var rows = bomService.GetBomApproveTrans(id);
        return Json(new
        {
          draw = 1,
          recordsTotal = rows.Count,
          recordsFiltered = rows.Count,
          data = rows
        });
      }
      catch (System.Exception)
      {

        throw;
      }
    }

    // end
  }
}

Views/Bom/ApproveList.cshtml
@{
    ViewData["Title"] = "Approve List";
}

@model ApproveListViewModel
@using Deestone.Services

@{
    BomService bomService = new BomService();
}

<div class="box" style="max-width: 800px; margin: auto;">
    <div class="box-body">
        <form id="formApprove" asp-controller="BomApi" asp-action="SubmitApprove" method="post">
            <table>
                @foreach (var item in Model.BOMLISTAPPROVE)
                {
                    <tr>
                        <td style="padding: 5px;" valign="middle">@item.BOMID</td>
                        <td style="padding: 5px;" valign="middle">
                            <a href="/bom/bomdetail?bomid=@item.BOMID" target="_blank" style="margin: 0px 10px;">รายละเอียด</a>
                        </td>
                        <td style="padding: 5px;" valign="middle">
                            อนุมัติ/ไม่อนุมัติ <br />
                            @{ var _n = "approve_" + item.BOMID + "_" + item.BOM_RECID; }
                            <select style="width: 150px;" name="@_n">
                                <option value='0'>-- เลือก --</option>
                                <option value='1'>อนุมัติ</option>
                                <option value='2'>ไม่อนุมัติ</option>
                            </select>
                        </td>
                        <td style="padding: 5px;" valign="middle">เหตุผล <br /> <textarea cols="50" rows="5" name="reason_@item.BOMID"></textarea></td>
                    </tr>

                    @if (Model.BOM_RECID.Count > 0)
                    {
                        @foreach(var bomRecId in Model.BOM_RECID)
                        {

                            @if (bomRecId.BOM_RECID == item.BOM_RECID)
                            {
                                <tr>
                                    <td colspan="4" style="padding: 10px 0px;">
                                        <p style="font-weight: bold;">หมายเหตุเพิ่มเติม</p>
                                    </td>
                                </tr>
                                @foreach (var remark in bomService.GetBomRemarkByBomId(bomRecId.BOM_RECID))
                                {
                                    <tr>
                                        <td colspan="4" bgcolor="#eeeeee" style="padding: 10px;">
                                            <p>
                                                @if (remark.APPROVE == 1)
                                                {
                                                    <span>(อนุมัติ)</span>
                                                }
                                                else
                                                {
                                                    <span>(ไม่อนุมัติ)</span>
                                                }

                                                @remark.EMPNAME : @remark.REMARK
                                            </p>
                                        </td>
                                    </tr>
                                }
                            }
                        }
                    }
                }
            </table>

            <div class="form-group" style="margin: 20px 0px;">
                @Html.AntiForgeryToken()
                <input type="hidden" name="email" value="@Model.EMAIL" />
                <input type="hidden" name="nonce" value="@Model.NONCE" />
                <button class="btn btn-success" type="submit">บันทึกข้อมูล</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        jQuery(document).ready(function($) {
            $("#formApprove").submit(function (e) {
                if (confirm("คุณยืนยันที่จะดำเนินการต่อ?")) {
                    $("button[type=submit]").prop("disabled", true).text("กำลังประมวลผล...");
                } else {
                    e.preventDefault();
                }
            });
        });
    </script>
}

Views/Bom/Bom.cshtml
@{ ViewData["Title"] = "Bom"; Layout = "MainLayout"; }

<table id="grid" class="compact stripe table-nowrap" style="width: 100%;">
  <thead>
    <tr>
      <th>#</th>
      <th>BOMID</th>
      <th>BOMNAME</th>
      <th>COMPANY</th>
      <th>STATUS</th>
      <th>CREATE DATE</th>
      <th>UPDATE DATE</th>
      <th>COMPLETE DATE</th>
      <th>AX STATUS</th>
    </tr>
    <tr>
      <th>#</th>
      <th>BOMID</th>
      <th>BOMNAME</th>
      <th>COMPANY</th>
      <th>STATUS</th>
      <th>CREATE DATE</th>
      <th>UPDATE DATE</th>
      <th>COMPLETE DATE</th>
      <th>AX STATUS</th>
    </tr>
  </thead>
</table>

<div class="modal" id="modalBomApprove" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">รายละเอียด</h4>
      </div>
      <div class="modal-body">
        <div style="overflow-x: scroll;">
          <table
            id="gridBomApproveTrans"
            class="compact stripe table-nowrap"
            style="width: 100%;"
          >
            <thead>
              <tr>
                <th>#</th>
                <th>BOMID</th>
                <th>EMAIL</th>
                <th>EMAIL_ORDER</th>
                <th>CREATE DATE</th>
                <th>SEND DATE</th>
                <th>SEND NOTIFY DATE</th>
                <th>APPROVE DATE</th>
                <th>REJECT DATE</th>
              </tr>
              <tr>
                <th>#</th>
                <th>BOMID</th>
                <th>EMAIL</th>
                <th>EMAIL_ORDER</th>
                <th>CREATE DATE</th>
                <th>SEND DATE</th>
                <th>SEND NOTIFY DATE</th>
                <th>APPROVE DATE</th>
                <th>REJECT DATE</th>
              </tr>
            </thead>
          </table>
        </div>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

@section Scripts {
<script>
  $(document).ready(function() {
    loadGrid({
      el: "#grid",
      dom: "Bfrtip",
      buttons: [
        {
          text: "รายละเอียด",
          action: function() {
            var rowdata = getRowsSelected("#grid");
            if (rowdata.length > 0) {
              $("#modalBomApprove").modal({ backdrop: "static" });

              loadGrid({
                el: "#gridBomApproveTrans",
                dom: "Bfrtip",
                buttons: [],
                processing: false,
                serverSide: false,
                deferRender: true,
                searching: true,
                order: [],
                orderCellsTop: true,
                destroy: true,
                select: {
                  style: "single",
                },
                ajax: {
                  url: "/bom/GetBomApproveTrans",
                  data: {
                    id: rowdata[0].ID,
                  },
                  method: "post",
                },
                columns: [
                  { data: "ID" },
                  { data: "BOMID" },
                  { data: "EMAIL" },
                  { data: "EMAIL_ORDER" },
                  { data: "DIMENSION"},
                  { data: "CREATE_DATE" },
                  { data: "SEND_DATE" },
                  { data: "SEND_NOTIFY_DATE" },
                  { data: "APPROVE_DATE" },
                  { data: "REJECT_DATE" },
                ],
                columnDefs: [
                  {
                    render: function(data, type, row) {
                      var c = dayjs(data).format("YYYY-MM-DD HH:mm:ss");

                      if (c === "1901-01-01 00:00:00") {
                        c = "";
                      }

                      return c;
                    },
                    targets: 4,
                  },
                  {
                    render: function(data, type, row) {
                      var c = dayjs(data).format("YYYY-MM-DD HH:mm:ss");

                      if (c === "1901-01-01 00:00:00") {
                        c = "";
                      }

                      return c;
                    },
                    targets: 5,
                  },
                  {
                    render: function(data, type, row) {
                      var c = dayjs(data).format("YYYY-MM-DD HH:mm:ss");

                      if (c === "1901-01-01 00:00:00") {
                        c = "";
                      }

                      return c;
                    },
                    targets: 6,
                  },
                  {
                    render: function(data, type, row) {
                      var c = dayjs(data).format("YYYY-MM-DD HH:mm:ss");

                      if (c === "1901-01-01 00:00:00") {
                        c = "";
                      }

                      return c;
                    },
                    targets: 7,
                  },
                  {
                    render: function(data, type, row) {
                      var c = dayjs(data).format("YYYY-MM-DD HH:mm:ss");

                      if (c === "1901-01-01 00:00:00") {
                        c = "";
                      }

                      return c;
                    },
                    targets: 8,
                  },
                ],
              });
            } else {
              alert("กรุณาเลือกรายการ");
            }
          },
        },
      ],
      processing: false,
      serverSide: false,
      deferRender: true,
      searching: true,
      order: [],
      orderCellsTop: true,
      destroy: true,
      select: {
        style: "single",
      },
      ajax: {
        url: "/bom/getbomall",
        method: "post",
      },
      columns: [
        { data: "ID" },
        { data: "BOMID" },
        { data: "BOMNAME" },
        { data: "COMPANY_REF" },
        { data: "STATUS" },
        { data: "CREATE_DATE" },
        { data: "UPDATE_DATE" },
        { data: "COMPLETE_DATE" },
        { data: "AX_STATUS" },
      ],
      columnDefs: [
        {
          render: function(data, type, row) {
            var c = dayjs(data).format("YYYY-MM-DD HH:mm:ss");

            if (c === "1901-01-01 00:00:00") {
              c = "";
            }

            return (
              '<div class="--create-date" data-pk="' +
              row.ID +
              '">' +
              c +
              "</div>"
            );
          },
          targets: 5,
        },
        {
          render: function(data, type, row) {
            var c = dayjs(data).format("YYYY-MM-DD HH:mm:ss");

            if (c === "1901-01-01 00:00:00") {
              c = "";
            }

            return (
              '<div class="--update-date" data-pk="' +
              row.ID +
              '">' +
              c +
              "</div>"
            );
          },
          targets: 6,
        },
        {
          render: function(data, type, row) {
            var c = dayjs(data).format("YYYY-MM-DD HH:mm:ss");

            if (c === "1901-01-01 00:00:00") {
              c = "";
            }

            return (
              '<div class="--complete-date" data-pk="' +
              row.ID +
              '">' +
              c +
              "</div>"
            );
          },
          targets: 7,
        },
        {
          render: function(data, type, row) {
            var c = "";
            if (+data === 1) {
              c = "Send to web.";
            } else if (+data === 4) {
              c = "Send to cancel";
            } else {
              c = data;
            }
            return (
              '<div class="--ax-status" data-pk="' +
              row.ID +
              '">' +
              c +
              "</div>"
            );
          },
          targets: 8,
        },
      ],
    });
  });
</script>
}

Views/Bom/SubmitResult.cshtml
@{
    ViewData["Title"] = "Submit Result";
    Layout = "CleanLayout";
}

<h1 class="text-center">@ViewData["Approve"] BOM VERSION @ViewData["BomId"]</h1>

<div class="text-center"
     style="margin: 30px auto;
    padding: 20px;
    border: 1px solid #cccccc;
    font-size: 1.3em;
    background: white;
    font-weight: bold;
    max-width: 700px;">

    @if (ViewData["isApprove"].ToString() == "1")
    {
        <form id="submitResult" asp-controller="BomApi" asp-action="ApproveBom" method="post">
            <div class="form-group">
                <label>หมายเหตุเพิ่มเติม</label>
                <textarea rows="10" name="remark" class="form-control"></textarea>
            </div>
            <div class="form-group">
                @Html.AntiForgeryToken()

                <input type="hidden" name="bom" value="@ViewData["BomRedId"]" />
                <input type="hidden" name="email" value="@ViewData["EmailRecId"]" />
                <input type="hidden" name="trans" value="@ViewData["ApproveTransId"]" />
                <input type="hidden" name="id" value="@ViewData["BomId"]" />
                <input type="hidden" name="company" value="@ViewData["Company"]" />
                <input type="hidden" name="nonce" value="@ViewData["Nonce"]" />

                <button type="submit" id="btnSubmit" class="btn btn-success" onclick="return confirm('ยืนยันที่จะบันทึกข้อมูล?')">บันทึกข้อมูล</button>
            </div>
        </form>
    }
    else
    {
        <form id="submitResult" asp-controller="BomApi" asp-action="RejectBom" method="post">
            <div class="form-group">
                <label>หมายเหตุเพิ่มเติม</label>
                <textarea rows="10" name="remark" class="form-control"></textarea>
            </div>
            <div class="form-group">
                @Html.AntiForgeryToken()

                <input type="hidden" name="bom" value="@ViewData["BomRedId"]" />
                <input type="hidden" name="email" value="@ViewData["EmailRecId"]" />
                <input type="hidden" name="trans" value="@ViewData["ApproveTransId"]" />
                <input type="hidden" name="id" value="@ViewData["BomId"]" />
                <input type="hidden" name="company" value="@ViewData["Company"]" />
                <input type="hidden" name="nonce" value="@ViewData["Nonce"]" />

                <button type="submit" id="btnSubmit" class="btn btn-success" onclick="return confirm('ยืนยันที่จะบันทึกข้อมูล?')">บันทึกข้อมูล</button>
            </div>
        </form>
    }



</div>

@section Scripts {
    <script>
        $("#submitResult").on("submit", function (e) {
            $("#btnSubmit").prop("disabled", true).text("กำลังประมวลผล...");
        });
    </script>
}